### ISSUE TITLE
docker compose部署以后，登录出现 request_throttled

### ISSUE THREAD

**Issue by Ankh2454** [coaidev/coai#272]
[//]: # (方框内删除已有的空格，填 x 号)
+ [ ] 我已确认目前没有类似 issue
+ [ ] 我已确认我已升级到最新版本
+ [ ] 我已完整浏览项目 README 和项目文档并未找到解决方案
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我将以礼貌和尊重的态度提问，不得使用不文明用语 (包括在此发布评论的所有人同样适用, 不遵守的人将被 block)
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**

**复现步骤**

**预期结果**

**日志信息**

**相关截图 (如果有)**

**Comment by Ankh2454** [comment]
/api/login 登录出现
{
    "error": "request_throttled",
    "reason": "You have sent too many requests. Please try again later.",
    "status": false
}

**Comment by zmh-program** [comment]
失败请求次数超过限制导致，等待即可
