### ISSUE TITLE
使用go build命令构建时出现“https://github.com/bincooo/requests/”无法安装

### ISSUE THREAD

**Issue by flesym** [coaidev/coai#284]
[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整浏览项目 README 和项目文档并未找到解决方案
+ [ ] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [ ] 我将以礼貌和尊重的态度提问，不得使用不文明用语 (包括在此发布评论的所有人同样适用, 不遵守的人将被 block)
+ [ ] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
执行命令“go build -o chatnio”后，执行到：
go: downloading github.com/bincooo/requests v0.0.0-20230720064210-7eae5d6c9d1e
这一行后，一直提示无法下载

**相关截图 **
![image](https://github.com/user-attachments/assets/7aa6bc9b-83bc-4df7-a3a5-219ca52e43d0)

**Comment by zmh-program** [comment]
#279
