### ISSUE TITLE
界面按钮颜色太淡

### ISSUE THREAD

**Issue by kitaev-chen** [coaidev/coai#302]
按钮选中与否的差别太小，最好还是醒目一点：

<img src="https://github.com/user-attachments/assets/90903185-6fce-4e59-a9b5-a0dcd1a9e6a5" alt="白" width="300" />

<img src="https://github.com/user-attachments/assets/43ba4957-b11f-4dd5-a762-8dafb98df6e1" alt="黑" width="300" />

**Comment by zmh-program** [comment]
#285 有立项，同步新 UI 至开源版。


> Commercial UI (Commercial UI Components, Design, Customizable Themes, etc.)
