### ISSUE TITLE
支持硅基流动(SiliconFlow)渠道

### ISSUE THREAD

**Issue by kitaev-chen** [coaidev/coai#303]
硅基流动(SiliconFlow)作为LLM时代的赛博菩萨，提供了很多免费模型，希望能支持！

免费模型列表：
![image](https://github.com/user-attachments/assets/dbdd6664-98fb-4853-9591-676a057a779c)

API调用快速上手：
https://docs.siliconflow.cn/quickstart

**Comment by zmh-program** [comment]
#227
