### ISSUE TITLE
支持百度千帆渠道

### ISSUE THREAD

**Issue by kitaev-chen** [coaidev/coai#304]
百度近期免费开放了部分模型并打算长期支持，可以考虑增加百度的渠道：

模型列表：
![image](https://github.com/user-attachments/assets/b9f964c7-226d-424a-9148-3c3183fd6738)

千帆ModelBuilder 部分ERNIE系列模型免费开放公告
https://cloud.baidu.com/doc/WENXINWORKSHOP/s/wlwg8f1i3

API文档
https://cloud.baidu.com/doc/WENXINWORKSHOP/s/6ltgkzya5

**Comment by zmh-program** [comment]
#227

**Comment by kitaev-chen** [comment]
> #277 下次建议看一下有没有已经提的

收到~
