### ISSUE TITLE
管理员修改用户密码导致用户无法正常登录

### ISSUE THREAD

**Issue by ThorinKong** [coaidev/coai#306]
[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整浏览项目 README 和项目文档并未找到解决方案
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我将以礼貌和尊重的态度提问，不得使用不文明用语 (包括在此发布评论的所有人同样适用, 不遵守的人将被 block)
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

**问题描述**
当管理员在后台修改用户的密码后，用户在前端登录填写新密码后页面右下角弹出登录成功弹窗，但页面仍呈现未登录状态。选择任意模型均提示“您需要登录才能使用此功能”。开启浏览器F12，登录login接口正常返回token，list接口显示message:"user not found"。重启服务后可正常登录。怀疑是token有效期之类的问题。
**复现步骤**

1 使用docker-compose部署服务
2 注册一个普通账户
3 使用管理员账户修改该账户的密码
4 普通账户使用新密码登录
5 普通账户无法正常使用

**预期结果**
普通账户能正常登录使用
**日志信息**
无
**相关截图 (如果有)**
![image](https://github.com/user-attachments/assets/119a327c-44fc-4a32-8ce8-5418eb68fc1a)

**Comment by zmh-program** [comment]
#285  will fix
