### ISSUE TITLE
Watchtower 服务 bug：反复重试访问 *.docker.io 可能导致服务崩溃

### ISSUE THREAD

**Issue by Xheldon** [coaidev/coai#308]
[//]: # (方框内删除已有的空格，填 x 号)
+ [x] 我已确认目前没有类似 issue
+ [x] 我已确认我已升级到最新版本
+ [x] 我已完整浏览项目 README 和项目文档并未找到解决方案
+ [x] 我理解并愿意跟进此 issue，协助测试和提供反馈
+ [x] 我将以礼貌和尊重的态度提问，不得使用不文明用语 (包括在此发布评论的所有人同样适用, 不遵守的人将被 block)
+ [x] 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则的 issue 可能会被无视或直接关闭**

使用的是 `docker-compose -f docker-compose.watch.yaml up -d` 命令，带 watch 的，部署完挺好的，隔夜发现服务挂了，重启正常，然后一直到现在都正常就没管了（可能因为我中途重启过几次，无意间掩盖了请求过多导致的问题）。

但是今天排查其他问题，无意间发现 watchtower 失败会一直重试，回想起这可能是之前导致这个服务挂掉的原因。

证据如图：

Surge 网络请求（注意这个是活动 tab，是是一直动态变化，一个请求 index.docker.io 失败后就从这个列表移除，然后又出现一个 index.docker.io 的请求，其他 *.docker.io 请求类似）

![CleanShot_2024_12_08_at_01_22_02@2x](https://github.com/user-attachments/assets/cd26a2c7-0257-4d72-a408-0a0e4b4d1535)

docker 内的 chatnio 日志：（注意看右下角，很长的日志，这才启动不到1分钟！）

![CleanShot_2024_12_08_at_01_23_46@2x](https://github.com/user-attachments/assets/718086e2-23e0-4d02-9b06-744c08256e7b)

**Comment by Xheldon** [comment]
另外还有一个小问题我就不单独提 issue 了，就是后台管理里面的服务日志，点击删除了 chatnio.log 日志后，就再也获取不到新日志了（提示找不到文件），刷新也没用，除非重启 docker 服务才行。

**Comment by zmh-program** [comment]
> 另外还有一个小问题我就不单独提 issue 了，就是后台管理里面的服务日志，点击删除了 chatnio.log 日志后，就再也获取不到新日志了（提示找不到文件），刷新也没用，除非重启 docker 服务才行。

这个我记得好久之前修复过，禁止删除latest log chunk，不知道开源版下没下放。后续 #285 会修复。

**Comment by zmh-program** [comment]
已从 30s 设置到 3600s。 git pull 一下重新启动。 未复现，大概率的原因是未携带 docker credentials 因此导致速率限制。
如仍有问题，请 reopen 此 issue。
